import json
from pathlib import Path

from .models import MemoryRecord


def load_records(path: Path) -> list[MemoryRecord]:
    if not path.exists():
        return []
    payload = json.loads(path.read_text())
    return [MemoryRecord.from_dict(item) for item in payload.get("memories", [])]


def save_records(path: Path, records: list[MemoryRecord]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {"version": 1, "memories": [record.to_dict() for record in records]}
    path.write_text(json.dumps(payload, indent=2) + "\n")


def render_markdown(records: list[MemoryRecord]) -> str:
    lines = ["# Project Memory", "", "Generated by MemVet.", ""]
    for record in records:
        lines.extend(
            [
                f"## {record.title}",
                "",
                f"- Status: `{record.status}`",
                f"- Memory ID: `{record.id}`",
                f"- Introduced by: `{record.introduced_commit}`",
            ]
        )
        if record.verified_commit:
            lines.append(f"- Verified at: `{record.verified_commit}`")
        if record.verified_tests:
            lines.append(
                f"- Verified tests: {', '.join(f'`{item}`' for item in record.verified_tests)}"
            )
        if record.verification_command:
            lines.append(f"- Verification command: `{record.verification_command}`")
        if record.verification_evidence:
            provider = record.verification_evidence.get("provider", "unknown")
            outcome = record.verification_evidence.get("outcome", "unknown")
            lines.append(f"- Verification evidence: `{provider}` / `{outcome}`")
        if record.files:
            lines.append(f"- Files: {', '.join(f'`{item}`' for item in record.files)}")
        if record.symbols:
            lines.append(f"- Symbols: {', '.join(f'`{item}`' for item in record.symbols)}")
        if record.tests:
            lines.append(f"- Tests: {', '.join(f'`{item}`' for item in record.tests)}")
        lines.extend(["", record.content, ""])
    return "\n".join(lines)
