from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

from .audit import AuditReport
from .providers import CodeReference


@dataclass
class ReviewReport:
    audit: AuditReport
    external_findings: Sequence[CodeReference] = field(default_factory=tuple)
    provider_errors: Sequence[str] = field(default_factory=tuple)

    @property
    def requires_review(self) -> bool:
        return self.audit.requires_review

    def to_dict(self) -> dict:
        return {
            "audit": self.audit.to_dict(),
            "external_findings": [
                {
                    "path": finding.path,
                    "symbol": finding.symbol,
                    "excerpt": finding.excerpt,
                    "source": finding.source,
                    "line_start": finding.line_start,
                    "line_end": finding.line_end,
                    "status": "external_unverified",
                }
                for finding in self.external_findings
            ],
            "provider_errors": list(self.provider_errors),
        }

    def to_markdown(self) -> str:
        verdict = "REVIEW REQUIRED" if self.requires_review else "PASS"
        lines = [
            "## MemVet review",
            "",
            f"**Verdict:** `{verdict}`",
            f"**Base:** `{self.audit.base}`",
            f"**HEAD:** `{self.audit.head}`",
            f"**Changed files:** {len(self.audit.changed_files)}",
            "",
        ]

        if self.audit.items:
            lines.append("### Memory findings")
            lines.append("")
            for item in self.audit.items:
                lines.extend(
                    [
                        f"- **{item.action}** `{item.id}` — {item.title} (`{item.status}`)",
                        f"  - Files: {', '.join(item.files) or 'none'}",
                    ]
                )
                lines.extend(f"  - {reason}" for reason in item.reasons)
            lines.append("")
        else:
            lines.extend(
                [
                    "### Memory findings",
                    "",
                    "No tracked memories are affected by this change.",
                    "",
                ]
            )

        if self.external_findings:
            lines.extend(["### External code context", ""])
            for finding in self.external_findings:
                location = finding.path or "unknown path"
                if finding.line_start is not None:
                    location += f":{finding.line_start}"
                    if finding.line_end is not None:
                        location += f"-{finding.line_end}"
                lines.append(
                    f"- `{location}` — `{finding.source}` — `external_unverified`"
                )
                if finding.excerpt:
                    lines.append(f"  - {finding.excerpt}")
            lines.append("")

        if self.provider_errors:
            lines.extend(["### Provider warnings", ""])
            lines.extend(f"- {error}" for error in self.provider_errors)
            lines.append("")

        lines.extend(
            [
                "### Recommended action",
                "",
                (
                    "Revalidate affected memories and run their recorded tests before reuse."
                    if self.requires_review
                    else "No memory action is required for this pull request."
                ),
                "",
                "_Generated by MemVet. External provider results are leads, not verification._",
            ]
        )
        return "\n".join(lines)


def review_repository(
    repo: Path,
    base: str,
    *,
    greptile_provider=None,
    query: str | None = None,
    limit: int = 10,
) -> ReviewReport:
    from .audit import audit_repository
    from .git import changed_paths
    from .ledger import load_records

    audit = audit_repository(repo, base, load_records(repo / ".memvet" / "memories.json"))
    findings: list[CodeReference] = []
    errors: list[str] = []
    if greptile_provider:
        changed = sorted(changed_paths(repo, base))
        search_query = query or (
            "Review the implementation and risks in changed files: "
            + ", ".join(changed)
        )
        try:
            findings = list(greptile_provider.search(search_query, limit=limit))
        except Exception as error:
            errors.append(f"Greptile unavailable: {error}")
    return ReviewReport(audit, findings, errors)
